### ISSUE TITLE
void froge theorey

### ISSUE THREAD

**Issue by actualdankcoder** [Murgn/sadfrogroll#10]
![image](https://user-images.githubusercontent.com/60839576/127759717-a1fa94e5-5f94-4696-917c-15e0b17e9cad.png)

![image](https://user-images.githubusercontent.com/60839576/127759712-ead92a1c-b50a-4823-a6c4-c8b811ba2555.png)

![image](https://user-images.githubusercontent.com/60839576/127759721-8bfacdad-4f68-4d27-868a-cd906d469902.png)

Using [Heisenberg's Uncertainty Principle](https://en.wikipedia.org/wiki/Uncertainty_principle), we can evaluate the theorey of finding a froge in a void

![image](https://user-images.githubusercontent.com/60839576/127759765-cac99b47-aed4-4f78-bf80-26a00435d19c.png)
![image](https://user-images.githubusercontent.com/60839576/127759773-cf7e4358-72f6-4273-a46b-814af9164ca2.png)

Which as shown above, comes to be 38.6nm near a black hole. Though this assumption is only valid if our frogeg went through a [Large Hadron Particle Accelerator](https://en.wikipedia.org/wiki/Large_Hadron_Collider) and attained a velocity of 4.473 million miles per hour

**Comment by Taromaruu** [comment]
this is very interesting, will consider.
