### ISSUE TITLE
Am i meant to be able to scroll through your webapp? :pikathonk:

### ISSUE THREAD

**Issue by AakashSharma7269** [Murgn/sadfrogroll#11]
https://user-images.githubusercontent.com/60808802/129453138-d8a89cf4-3236-42bc-8929-bab2565d680f.mp4

**Comment by Taromaruu** [comment]
@AakashSharma7269 I cannot play the video on Firefox. Can you upload it somewhere else?

**Comment by AakashSharma7269** [comment]
Uhh I uploaded it directly to github, shouldn't be an issue. Can you try wget or curl on the file?
I already deleted it and it's 4am

**Comment by Murgn** [comment]
Video worked fine for me, will fix soon.

**Comment by actualdankcoder** [comment]
Cannot replicate in the browser referenced in the video, the issueholder's browser extensions might have contributed to it

**Comment by Taromaruu** [comment]
It still will help to disable the scroll bar.

**Comment by Murgn** [comment]
The scrollbar is already disabled, like denc said, it might be an extension

**Comment by AakashSharma7269** [comment]
I am using the vimium extension, but it still looks like a bug to me.

**Comment by AakashSharma7269** [comment]
Maybe a won't fix but yea, a bug nonetheless.
