### ISSUE TITLE
froge get dizy

### ISSUE THREAD

**Issue by actualdankcoder** [Murgn/sadfrogroll#5]
froge get dizy when roll much, pleas fixe

**Comment by Taromaruu** [comment]
fixed. made `Frog.get_dizzy = false;`

**Comment by evilbryan590** [comment]
I didn't see the fix in the code. What happened?

**Comment by Taromaruu** [comment]
> I didn't see the fix in the code. What happened?

Sorry I forgot to push. I'll push tomorrow :))
